services:
  sql:
    container_name: sql
    image: mysql:8.0
    restart: always
#    ports:
#      - "127.0.0.1:3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_boot_security

  jre:
    container_name: jre
    image: eclipse-temurin:17-jre
    volumes:
      - ./target:/app/target
    working_dir: /app
    command: java -jar /app/target/demo-0.0.1-SNAPSHOT.jar
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
